# Given a list of numbers, return the N most frequent elements, sorted by frequency (highest first).
# lis = [1, 1, 2, 2, 2, 3, 4, 4], n = 2
# [2, 1] (2 appears 3 times, 1 appears 2 times — top 2 most frequent)

def top_n_freq(lis, n):
    dic = {}

    for i in range(len(lis)):
        if lis[i] in dic:
            dic[lis[i]] += 1
        else:
            dic[lis[i]] = 1
    # sorted by values
    sorted_dict = dict(sorted(dic.items(), key=lambda item: item[1], reverse=True))
    
    ## sorted_dic = dict(sorted(dic.items())) ## sorted by key
    
    sorted_list = list(sorted_dict) ### the list is generated by keys of the dic

    return sorted_list[:n]


lis = [1, 1, 2, 2, 2, 3, 3, 4, 4]
n = 2


result = top_n_freq(lis, n)
print(result)

